export const byEquipments: string[] = [
  'Assisted',
  'Band',
  'Barbell',
  'Body Weight',
  'Bosu Ball',
  'Cable',
  'Dumbbell',
  'Elliptical Machine',
  'Ez Barbell',
  'Hammer',
  'Kettlebell',
  'Leverage Machine',
  'Medicine Ball',
  'Olympic Barbell',
  'Resistance Band',
  'Roller',
  'Rope',
  'Skierg Machine',
  'Sled Machine',
  'Smith Machine',
  'Stability Ball',
  'Stationary Bike',
  'Stepmill Machine',
  'Tire',
  'Trap Bar',
  'Upper Body Ergometer',
  'Weighted',
  'Wheel Roller',
];

export const byMuscles: string[] = [
  'Abductors',
  'Abs',
  'Adductors',
  'Biceps',
  'Calves',
  'Cardiovascular System',
  'Delts',
  'Forearms',
  'Glutes',
  'Hamstrings',
  'Lats',
  'Levator Scapulae',
  'Pectorals',
  'Quads',
  'Serratus Anterior',
  'Spine',
  'Traps',
  'Triceps',
  'Upper Back',
];

export const byBodyParts: string[] = [
  'Back',
  'Cardio',
  'Chest',
  'Lower Arms',
  'Lower Legs',
  'Neck',
  'Shoulders',
  'Upper Arms',
  'Upper Legs',
  'Waist',
];
