import { Exercise } from '@/interfaces';

export const jsonData: Exercise[] = [
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/EJ4dGky6RWUxEG',
    id: '0001',
    name: '3/4 sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/M4CtG-dKZFN0i-',
    id: '0002',
    name: '45° side bend',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/BrFCiJ-zDjg4JD',
    id: '0003',
    name: 'air bike',
    target: 'abs',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/GsTgUTkdwnvKLt',
    id: '1512',
    name: 'all fours squad stretch',
    target: 'quads',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ibdY8Oq1VCA1I8',
    id: '0006',
    name: 'alternate heel touchers',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'cable',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/DQMVXT2uLEFGYv',
    id: '0007',
    name: 'alternate lateral pulldown',
    target: 'lats',
  },
  {
    bodyPart: 'lower legs',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/MHV9ndHCEmFK8d',
    id: '1368',
    name: 'ankle circles',
    target: 'calves',
  },
  {
    bodyPart: 'back',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/scrQycBR1W0LML',
    id: '3293',
    name: 'archer pull up',
    target: 'lats',
  },
  {
    bodyPart: 'chest',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/uAp1xqVctYdFqF',
    id: '3294',
    name: 'archer push up',
    target: 'pectorals',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/i4pmeajHWssxs9',
    id: '2355',
    name: 'arm slingers hanging bent knee legs',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/s1DeOnm-rQpQ8x',
    id: '2333',
    name: 'arm slingers hanging straight legs',
    target: 'abs',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Poddqg2QfksRmz',
    id: '3214',
    name: 'arms apart circular toe touch (male)',
    target: 'glutes',
  },
  {
    bodyPart: 'waist',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/2JecDuNo7elYoV',
    id: '3204',
    name: 'arms overhead full sit-up (male)',
    target: 'abs',
  },
  {
    bodyPart: 'chest',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/1pa-ZNiANTtx4Y',
    id: '0009',
    name: 'assisted chest dip (kneeling)',
    target: 'pectorals',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/dQTt8a37lcmgD0',
    id: '0011',
    name: 'assisted hanging knee raise',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/cDrsB1Z0QZJ5Lv',
    id: '0010',
    name: 'assisted hanging knee raise with throw down',
    target: 'abs',
  },
  {
    bodyPart: 'lower legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ZuGQgRcb9pJM0B',
    id: '1708',
    name: 'assisted lying calves stretch',
    target: 'calves',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/i3lu-0rCc-P5FR',
    id: '1709',
    name: 'assisted lying glutes stretch',
    target: 'glutes',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/KTZ-gkHq5lfgHU',
    id: '1710',
    name: 'assisted lying gluteus and piriformis stretch',
    target: 'glutes',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/MEalpkVfTI8gDp',
    id: '0012',
    name: 'assisted lying leg raise with lateral throw down',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/D2066Rvss2RnNd',
    id: '0013',
    name: 'assisted lying leg raise with throw down',
    target: 'abs',
  },
  {
    bodyPart: 'waist',
    equipment: 'medicine ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/bkjEpP4uMYORg0',
    id: '0014',
    name: 'assisted motion russian twist',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hDXFBKlXnSJ740',
    id: '0015',
    name: 'assisted parallel close grip pull-up',
    target: 'lats',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/XLDr4nc4urpF7n',
    id: '0016',
    name: 'assisted prone hamstring',
    target: 'hamstrings',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/p6MciNEMxKk79X',
    id: '1713',
    name: 'assisted prone lying quads stretch',
    target: 'quads',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/I8Au3HHehHnXbV',
    id: '1714',
    name: 'assisted prone rectus femoris stretch',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/BTqaRRZCbjF-cm',
    id: '0017',
    name: 'assisted pull-up',
    target: 'lats',
  },
  {
    bodyPart: 'chest',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xkhg27iWzOEfOk',
    id: '1716',
    name: 'assisted seated pectoralis major stretch with stability ball',
    target: 'pectorals',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/Do56qBcUBfKX5f',
    id: '1712',
    name: 'assisted side lying adductor stretch',
    target: 'adductors',
  },
  {
    bodyPart: 'waist',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/uaVCOYcuKUdQK9',
    id: '1758',
    name: 'assisted sit-up',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/qAkJ7rS7L0FMKY',
    id: '1431',
    name: 'assisted standing chin-up',
    target: 'lats',
  },
  {
    bodyPart: 'back',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hejpaUySP6UQtA',
    id: '1432',
    name: 'assisted standing pull-up',
    target: 'lats',
  },
  {
    bodyPart: 'upper arms',
    equipment: 'assisted',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xhfJlgZFntH7W0',
    id: '0018',
    name: 'assisted standing triceps extension (with towel)',
    target: 'triceps',
  },
  {
    bodyPart: 'upper arms',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/8mTsEeMf4Ymcpm',
    id: '0019',
    name: 'assisted triceps dip (kneeling)',
    target: 'triceps',
  },
  {
    bodyPart: 'chest',
    equipment: 'leverage machine',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/1fArMjeGNk2ocJ',
    id: '2364',
    name: 'assisted wide-grip chest dip (kneeling)',
    target: 'pectorals',
  },
  {
    bodyPart: 'cardio',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/AX5ePcYkO7oTLZ',
    id: '3220',
    name: 'astride jumps (male)',
    target: 'cardiovascular system',
  },
  {
    bodyPart: 'cardio',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LieUwzUeQmENOl',
    id: '3672',
    name: 'back and forth step',
    target: 'cardiovascular system',
  },
  {
    bodyPart: 'back',
    equipment: 'stability ball',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/9-KnpI0CbO6J4H',
    id: '1314',
    name: 'back extension on exercise ball',
    target: 'spine',
  },
  {
    bodyPart: 'back',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/hvGKRGg1QPUENl',
    id: '3297',
    name: 'back lever',
    target: 'upper back',
  },
  {
    bodyPart: 'back',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/vJRR6WYjDlei6g',
    id: '1405',
    name: 'back pec stretch',
    target: 'lats',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/UVT99am4bHWxLa',
    id: '1473',
    name: 'backward jump',
    target: 'quads',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'body weight',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/-AwmGlCOqvOc57',
    id: '0020',
    name: 'balance board',
    target: 'quads',
  },
  {
    bodyPart: 'upper arms',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/gKMSyc497XPtlj',
    id: '0968',
    name: 'band alternating biceps curl',
    target: 'biceps',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/xo-5diBI0hTxjT',
    id: '0969',
    name: 'band alternating v-up',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/v5RC7jMY2eGHdX',
    id: '0970',
    name: 'band assisted pull-up',
    target: 'lats',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/0vH76STnwaxj-J',
    id: '0971',
    name: 'band assisted wheel rollerout',
    target: 'abs',
  },
  {
    bodyPart: 'chest',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/87Lhh5rndWJT27',
    id: '1254',
    name: 'band bench press',
    target: 'pectorals',
  },
  {
    bodyPart: 'upper legs',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/qk2m5IurlNUaBK',
    id: '0980',
    name: 'band bent-over hip extension',
    target: 'glutes',
  },
  {
    bodyPart: 'waist',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/RErk4DNShPa7jz',
    id: '0972',
    name: 'band bicycle crunch',
    target: 'abs',
  },
  {
    bodyPart: 'back',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/S8XXdJ2t-Iwyx1',
    id: '0974',
    name: 'band close-grip pulldown',
    target: 'lats',
  },
  {
    bodyPart: 'upper arms',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/ynNkOcsEEWH5WV',
    id: '0975',
    name: 'band close-grip push-up',
    target: 'triceps',
  },
  {
    bodyPart: 'upper arms',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/LFQbDyKH-lNKl0',
    id: '0976',
    name: 'band concentration curl',
    target: 'biceps',
  },
  {
    bodyPart: 'back',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/lpb6INfjxiSX3C',
    id: '3117',
    name: 'band fixed back close grip pulldown',
    target: 'lats',
  },
  {
    bodyPart: 'back',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/MnfRR9FsAxtEIE',
    id: '3116',
    name: 'band fixed back underhand pulldown',
    target: 'lats',
  },
  {
    bodyPart: 'shoulders',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/5vl6YvRZagNfN3',
    id: '0977',
    name: 'band front lateral raise',
    target: 'delts',
  },
  {
    bodyPart: 'shoulders',
    equipment: 'band',
    gifUrl: 'https://edbv2-ff7foj6vca-uc.a.run.app/image/sFn9IZX38vytRi',
    id: '0978',
    name: 'band front raise',
    target: 'delts',
  },
];
